{
 "title": "New dashboard",
 "time": { "from": "2022-01-15T19:44:40.342Z", "to": "2022-01-16T00:27:51.482Z" },
 "panels": [
  {
   "title": "Качество продукта",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  quality_true,\n  quality_predict\nFROM fakedata\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "R2 метрика",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  max(datetime) as \"time\",\r\n  (1.0 - sum((quality_predict - quality_true)^2) / \r\n   sum((quality_true - (SELECT AVG(quality_true)\r\n                       FROM fakedata\r\n                       WHERE quality_true IS NOT NULL AND $__timeFilter(datetime)\r\n                      ))^2)) as r2\r\nFROM fakedata\r\nWHERE\r\n  quality_true IS NOT NULL AND quality_true IS NOT NULL\r\n  AND $__timeFilter(datetime)\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MAE метрика",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(datetime) AS \"time\",\n  AVG(ABS(quality_true - quality_predict)) as mae\nFROM fakedata\nWHERE\n  $__timeFilter(datetime)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  AVG(temperature) OVER (ORDER BY datetime ROWS BETWEEN 30 PRECEDING AND CURRENT ROW)\nFROM fakedata\nWHERE\n  $__timeFilter(datetime)\n  AND temperature IS NOT NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Загрузка, кг/ч",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  AVG(loading) OVER(ORDER BY datetime ROWS BETWEEN 30 PRECEDING AND CURRENT ROW) as \"loading\"\nFROM fakedata\nWHERE\n  $__timeFilter(datetime)\n  AND loading IS NOT NULL\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Давление",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  avg(pressure) OVER (ORDER BY datetime ROWS BETWEEN 30 PRECEDING AND CURRENT ROW) AS \"pressure\"\nFROM fakedata\nWHERE\n  $__timeFilter(datetime)\n  AND pressure IS NOT NULL\nORDER BY 1"
    }
   ]
  }
 ]
}